### ISSUE TITLE
Using lightbody with jetty-server:jar:9.0.6.v20130930

### ISSUE THREAD

**Issue by mohamed-gaber** [lightbody/browsermob-proxy#103]
I'm trying to use the proxy code with a newer jetty version but it gives me this error
java.lang.NoSuchMethodError: org.eclipse.jetty.util.UrlEncoded.decodeTo(Ljava/lang/String;Lorg/eclipse/jetty/util/MultiMap;Ljava/lang/String;)

It seems that the function decodeTo in the new version has an additional parameter so it raises this exception. Could you please make a new release which depends on a newer jetty version and fix this issue?
Thanks.

**Comment by andy-zhang-guohua** [comment]
I'm running into same issue, could anyon help ? I'm using :
		<dependency>
			<groupId>net.lightbody.bmp</groupId>
			<artifactId>browsermob-proxy</artifactId>
			<version>2.0.0</version>
		</dependency>

**Comment by jekh** [comment]
Unfortunately, 2.0.0 is _not_ compatible with Jetty 9. It has a hard dependency on Servlet API 2.5, and using Servlet API 3.0+ causes several issues.

In the 2.1.0 branch in master, it should theoretically be possible to produce a browsermob-core shaded artifact that you could embed in a Jetty 8 or 9 application. That would take some tinkering with the maven-shade-plugin in the browsermob-core pom file, but I would welcome any PR that does so.

In 2.1.x the Jetty 5 code will eventually be optional, and in 3.0 we are planning to remove the Jetty 5 code entirely, so that will eliminate the compatibility issues with Jetty 8 and 9. But that's still a ways down the line, unfortunately.

**Comment by jekh** [comment]
This issue should now be resolved when using the LittleProxy implemenation. Make sure to _not_ include browsermob-core in your pom, only browsermob-core-littleproxy. Let me know if you still run into these problems.

**Comment by jayantsarda** [comment]
What pom dependency should we be using instead of 
net.lightbody.bmp
browsermob-proxy
2.0.0

We can not upgrade to browsermob 3.0 at this point

**Comment by jekh** [comment]
If you want to avoid the Jetty 9 conflict, your only option is to use the LittleProxy implementation. Version 2.1.0 was just released. The legacy implementation is not being actively developed, and no further enhancements/fixes/etc. are planned for it.

**Comment by jayantsarda** [comment]
Thanks for quick response. I added below dependancy but i still see same issue. I tried to exclude "browsermob-core" but that did not help either .. any further pointers?
net.lightbody.bmp
browsermob-proxy
2.1.0 ..
